version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
    post_build:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files: target/lambda-java-example-1.0-SNAPSHOT.jar
      
