version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - aws cloudformation package --template-file template.yaml --s3-bucket gpfanout --output-template-file newtemplate.yaml
    post_build:
      - echo Build completed on `date`
artifacts:
  files: 
    - target/lambda-java-example-1.0-SNAPSHOT.jar
    - newtemplate.yaml  
